on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  node-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Standardize on LTS
          cache: "npm"
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Quality Checks
        # Run standard scripts. Using --if-present keeps it from failing
        # if a specific project doesn't need one of these.
        run: |
          npm run lint --if-present
          npm run typecheck --if-present
          npm test --if-present
          npm run build --if-present
