name: "Build Typedoc Documentation"
description: "Checks out code, installs dependencies, and runs the documentation build command."

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Npm install
      run: npm ci
      shell: bash

    - name: Copy Typedoc Base Config
      shell: bash
      run: cp "${GITHUB_ACTION_PATH}/${{ inputs.base_config_path }}" ./typedoc.base.json

    - name: Build doc (Run typedoc)
      shell: bash
      run: npm run generate:code-docs
