name: "Build Typedoc Documentation"
description: "Checks out code, installs dependencies, and runs the documentation build command."

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Npm install
      working-directory: ${{ github.action_path }}
      run: npm install
      shell: bash

    - name: Generate Dynamic TypeDoc Config
      shell: bash
      working-directory: ${{ github.action_path }}
      run: node "${{ github.action_path }}/generate-typedoc-config.js"

    - name: Build doc (Run typedoc)
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Add the SHARED binary folder to the PATH temporarily
        export PATH="${{ github.action_path }}/node_modules/.bin:$PATH"

        # Execute typedoc. 
        # - It runs in CWD (Workspace), so it finds tsconfig.json and typedoc.json automatically.
        # - We explicitly point to the plugin in the shared folder so it can be found.
        typedoc \
          --options typedoc.json \
          --plugin "${{ github.action_path }}/node_modules/typedoc-plugin-markdown"
