name: "Build Typedoc Documentation"
description: "Checks out code, installs dependencies, and runs the documentation build command."

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Npm install
      working-directory: ${{ github.action_path }}
      run: npm install
      shell: bash

    - name: Generate Dynamic TypeDoc Config
      shell: bash
      run: node "${{ github.action_path }}/generate-typedoc-config.js"

    - name: Generate Docs
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        # We execute the binary located in the SHARED action folder.
        # But we run it HERE, in the workspace root.

        "${{ github.action_path }}/node_modules/.bin/typedoc" \
          --options "typedoc.json" \
          --plugin "${{ github.action_path }}/node_modules/typedoc-plugin-markdown"
