name: Build Typedoc Documentation
description: "Generates documentation using internal Typedoc configuration."

runs:
  using: "composite"
  steps:
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Generate Docs
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        echo "🚀 Generating TS docs using action-internal config..."
        # We point --options to the file inside the action directory
        # We point --out to the standardized docs_dist folder
        npx --yes \
          -p typescript \
          -p typedoc@^0.28.15 \
          -p typedoc-plugin-markdown@^4.9.0 \
          typedoc \
            --options "${{ github.action_path }}/typedoc.json" \
            --out "${{ github.workspace }}/docs_dist" \
            --plugin typedoc-plugin-markdown
