name: "Build Python Docs"
description: "Installs dependencies and builds Sphinx documentation."

inputs:
  working-directory:
    description: "The directory containing pyproject.toml"
    required: false
    default: "."
  docs-directory:
    description: "The directory containing the Sphinx conf.py"
    required: false
    default: "docs"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Install Project for Docs
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry install --no-interaction --no-root

    - name: Build Sphinx Docs
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
      run: |
        poetry run sphinx-build -b html ${{ inputs.docs-directory }} ${{ inputs.docs-directory }}/_build/html

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-docs
        path: ${{ inputs.working-directory }}/${{ inputs.docs-directory }}/_build/html
