name: "Build Python Docs"
description: "Installs dependencies and builds Sphinx documentation."

inputs:
  working-directory:
    description: "The directory containing pyproject.toml"
    required: false
    default: "."
  docs-directory:
    description: "The directory containing the Sphinx conf.py"
    required: false
    default: "docs"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Install Project for Docs
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry install --no-interaction --no-root

    - name: Build Sphinx Docs
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
      run: |
        TOOLING_DIR="${{ github.action_path }}"
        VENV_PATH="$(poetry --directory "$TOOLING_DIR" env info --path)"
        OUTPUT_DIR="${DOCS_OUTPUT:-docs_dist}"
        DOCS_DIR="${{ inputs.docs-directory }}"
        "$VENV_PATH/bin/sphinx-build" -b html "$DOCS_DIR" "$OUTPUT_DIR"
