name: Release Package
description: Centralized release logic for TS (NPM) and Python (Poetry).

inputs:
  project_type:
    description: "typescript or python"
    required: true
  BOT_TOKEN:
    required: true
  NPM_TOKEN:
    required: false
  PYPI_TOKEN:
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 1. Install all release tools INTO the action directory
    - name: Install Release Tools
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm install semantic-release \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/github \
          @semantic-release/npm

    - name: Run Semantic Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.BOT_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        # This is the magic fix for the "Module Not Found" error
        NODE_PATH: ${{ github.action_path }}/node_modules
      run: |
        # Select config based on project type
        if [ "${{ inputs.project_type }}" == "python" ]; then
          # Use the relative path to the shared config inside your repo
          CONFIG="--extends ${{ github.action_path }}/.releaserc.python.json"
        else
          # Standard TS config (assumed to be in the project root or another file)
          CONFIG=""
        fi

        # Run the local binary we just installed
        ${{ github.action_path }}/node_modules/.bin/semantic-release $CONFIG

    # 2. Python-specific post-release (Publishing)
    - name: Poetry Publish
      if: ${{ inputs.project_type == 'python' }}
      shell: bash
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ inputs.PYPI_TOKEN }}
      run: |
        pipx install poetry
        # Get the new tag created by semantic-release
        NEW_TAG=$(git describe --tags --abbrev=0 | sed 's/v//')
        poetry version $NEW_TAG
        poetry build
        if [ -n "$POETRY_PYPI_TOKEN_PYPI" ]; then
          poetry publish
        fi
