name: Release Package
description: Makes a release of the package

inputs:
  BOT_TOKEN:
    description: The Bot Token for committing changes back to the repository.
    required: true
  NPM_TOKEN:
    description: Custom NPM auth token for private package access.
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Git user as GitHub actions
      shell: bash
      run: git config --global user.email "179917785+engineering-ci[bot]@users.noreply.github.com" && git config --global user.name "engineering-ci[bot]"

    - name: Use node 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Download built package artifact
      uses: actions/download-artifact@v4
      with:
        name: Package
        path: artifacts

    - name: Unzip package
      shell: bash
      run: unzip artifacts/package.zip -d dist

    - name: Install dependencies for semantic release
      shell: bash
      run: npm ci --prefix release-package --ignore-scripts

    - name: Run Semantic Release
      run: npx semantic-release@latest
      env:
        GITHUB_TOKEN: ${{ inputs.BOT_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
