name: Release Package
description: Logic to release either Node (NPM) or Python (Poetry) packages.

inputs:
  project_type:
    description: "Either 'typescript' or 'python'"
    required: true
  BOT_TOKEN:
    description: "GitHub Token"
    required: true
  NPM_TOKEN:
    description: "NPM Token (Required for TS)"
    required: false
  PYPI_TOKEN:
    description: "PyPI Token (Required for Python)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node (For Semantic Release)
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run Semantic Release
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.BOT_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: |
        # Determine which config to use
        if [ "${{ inputs.project_type }}" == "python" ]; then
          CONFIG="--extends ./.releaserc.python.json"
        else
          # Assumes the standard .releaserc.json exists for TS
          CONFIG="" 
        fi

        npx semantic-release $CONFIG

    # --- POST-RELEASE PUBLISH (PYTHON) ---
    - name: Poetry Publish
      if: ${{ inputs.project_type == 'python' }}
      shell: bash
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ inputs.PYPI_TOKEN }}
      run: |
        # Get the new version created by semantic-release (from git tags)
        NEW_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
        poetry version $NEW_VERSION
        poetry build
        if [ -n "$POETRY_PYPI_TOKEN_PYPI" ]; then
          poetry publish
        else
          echo "No PYPI_TOKEN provided, skipping publish."
        fi
