name: "Zip and Upload Build Artifact"
description: "Zips the build folder and uploads it as a GitHub artifact."

inputs:
  build-path:
    description: "The folder containing the build output (e.g., 'dist')."
    required: false
    default: "dist"
  artifact-name:
    description: "The name for the final artifact/zip file."
    required: false
    default: "node-artifact"
  working-directory:
    description: "The working directory."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # Remove the manual "Zip build folder" step entirely

    - name: ⬆️ Upload Folder Directly
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.build-path }}
        if-no-files-found: error
